services:
  nodered:
    image: jardelc/node-red:4.0
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: nodered
    ports:
      - "1881:1880"
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_REPO=${GIT_REPO}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
      - NODE_RED_ENABLE_PROJECTS=true
